# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 2ea3ebd3-0b83-59a7-8974-c6f1b7780255

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerregisteryfuel.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c6d4c21c858a45b5b68730bc66f10263 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8a10f700153044fa9cf2a353dec29c26 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerregisteryfuel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c6d4c21c858a45b5b68730bc66f10263 }}/azurebotimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '2ea3ebd3-0b83-59a7-8974-c6f1b7780255'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dcd783a4832d476cb5876d167b86f06c }}
        images: 'containerregisteryfuel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c6d4c21c858a45b5b68730bc66f10263 }}/azurebotimage:${{ github.sha }}'